# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: 'MyAgentPool'

variables:
  buildConfiguration: 'Release'
  dockerImageName: 'stockapi'

steps:
- task: DotNetCoreCLI@2
  inputs:
   command: 'restore'
   feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Output'

#Your build pipeline references an undefined variable named ‘Parameters.buildContext’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
- task: Docker@1
  displayName: 'Build Docker Image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub Service Connection aditheppru'
    dockerFile: StockApi/Dockerfile
    imageName: 'stockapi:$(Build.BuildId)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: '$(Build.SourcesDirectory)'

- task: Docker@1
  displayName: 'Tag Docker Image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub Service Connection aditheppru'
    command: 'Tag image'
    arguments: 'stockapi:$(Build.BuildId) aditheppru/stockapi'
    imageName: 'stockapi:$(Build.BuildId)'
    qualifySourceImageName: true

- task: Docker@1
  displayName: 'Push Docker Image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub Service Connection aditheppru'
    imageName: 'aditheppru/stockapi:$(Build.BuildId)'
    command: 'Push an image'
    includeSourceTags: true
